#!/bin/bash

if [[ $# -ne 1 ]]; then
	echo "Usage: $0 <filename>"
	exit 1
fi

if [[ "$1" != *.img ]]; then
	echo "Filename needs to be .img"
	exit 1
fi

set -xe

if ! which rkdeveloptool &>/dev/null; then
	cat <<EOF
Please install rkdeveloptool and try again!

git clone https://github.com/rockchip-linux/rkdeveloptool --depth=1 --single-branch"
cd rkdeveloptool"
./configure
make
sudo make install
EOF
fi

wget -c https://github.com/ayufan-rock64/rkbin/raw/master/rk33/rk3328_loader_ddr786_v1.06.243.bin
if ! rkdeveloptool rid; then
	rkdeveloptool db rk3328_loader_ddr786_v1.06.243.bin
fi

for i in 1 2 3 4 5; do
	rkdeveloptool rid && break
	sleep 1
done

rkdeveloptool wl 0 "$1"
rkdeveloptool rd
